
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8088
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest


topics:
  notification-topic: notification

