server:
  port: 8081

spring:
  application:
    name: api-service
  config:
    import: optional:configserver:http://localhost:8088
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/danger
    username: pdursley
    password: Q1234qwe
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

topics:
  notification-topic: send
#  danger-event: danger

request:
  mapping: /api/v1/user

endpoints:
  show-user: ${request.mapping}/
  show-friends: ${request.mapping}/friends/
  show-subscribers: ${request.mapping}/subscribers/
  add-friends: ${request.mapping}/add/
  confirmation-friends: ${request.mapping}/confirm/

redis:
  host: 127.0.0.1
  port: 6379
  password: 12345678

user-service:
  health-endpoint: http://user-service/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health