spring:
  application:
    name: api-service
  config:
    import: optional:configserver:http://localhost:8088
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/octopus
    username: pdursley
    password: Q1234qwe
    driver-class-name: com.mysql.cj.jdbc.Driver

