spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/v1/send/**
        - id: user-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/v1/user/**

server:
  port: 9090
