server:
  port: 9090

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
#      routes:
#        - id: api-service
#          uri: http://127.0.0.1:8081
#          predicates:
#            - Path=/api/v1/send/**
#        - id: user-service
#          uri: http://127.0.0.1:8082
#          predicates:
#            - Path=/api/v1/user/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
