logging:
  level:
    org.springframework.cloud.gateway: DEBUG


server:
  port: 9090

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/v1/send/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/auth/**

        - id: health-check
          uri: http://127.0.0.1:8082 # Используем базовый URL, без /actuator
          predicates:
            - Path=/health/user-service/**
          filters:
            - RewritePath=/health/user-service/(?<remaining>.*), /actuator/${remaining}

      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 548DC890C4B6535BDF6F2D5199C5CFBA22041086DBD5052FEBAFD9E3A0321F69
