server:
  port: 8761

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: registry-service
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
