server:
  port: 9000

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8088
#  kafka:
#    bootstrap-servers: localhost:29093
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        acks: 1
#        spring:
#          json:
#            add:
#              type:
#                headers: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400

#topics:
#  registration: registration