server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8088
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: "order-2"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/octopus
    username: pdursley
    #    password: Q1234qwe #for Mac
    password: Q1234qwe__ #for Linux
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

topics:
  notification-topic: notification