server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8088
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: "order-2"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: pdursley
    password: Q1234qwe
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
