logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG


server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8088
  kafka:
    bootstrap-servers: kafka:29093
    consumer:
      group-id: "order-2"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

management:
  endpoint:
    health:
      enabled: true