server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8088
  kafka:
    bootstrap-servers: localhost:29092 #,localhost:29093
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  mail:
    host: smtp.gmail.com
    port: 587
#    username: nekkimark2@gmail.com
    username: gamrekelino@gmail.com
#    password: eyefelyfhorhxkmw
    password: bilt zilg nclk gofe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


topics:
  notification-topic: send

